// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import exchangeRateTrack "github.com/vaksi/foreign_currency/internal/exchangeRateTrack"
import mock "github.com/stretchr/testify/mock"

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *RepositoryFactory) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: _a0
func (_m *RepositoryFactory) Store(_a0 *exchangeRateTrack.ExchangeRateTrack) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*exchangeRateTrack.ExchangeRateTrack) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
